baseURL = "https://tsojka.com/"
languageCode = "de-de"
title = "tsojka.com – Car-HiFi-Kanal"
theme = "PaperMod"
ignoreLogs = ['warning-goldmark-raw-html']

[params]
  author = "Thomas Sojka"
  description = "Willkommen auf tsojka.com – deinem Car-HiFi-Kanal! Tutorials, Reviews und Tipps aus der Community, für die Community."

[[menu.main]]
  name = "Startseite"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Über mich"
  url = "/about"
  weight = 2

[[menu.main]]
  name = "Videos"
  url = "/videos"
  weight = 3

[[menu.main]]
  name = "Testlabor"
  url = "/testlabor"
  weight = 4

[[menu.main]]
  name = "Kontakt"
  url = "/kontakt"
  weight = 5

[[menu.main]]
  name = "Impressum"
  url = "/impressum"
  weight = 6